name: SelfOS Daily Summary

on:
  schedule:
    - cron: '0 21 * * *'  # Runs at 23:00 CET (21:00 UTC)
  workflow_dispatch:      # Optional to allow manual triggering

jobs:
  run-daily-summary:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/1021320164820/locations/global/workloadIdentityPools/selfos-pool/providers/github-provider'
          service_account: 'github-actions-sa@selfos-test.iam.gserviceaccount.com'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Inject secrets
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Run daily summary
        run: npm run summary -- --save