name: SelfOS Daily Summary

on:
  schedule:
    - cron: '0 21 * * *'  # 23:00 CET
  workflow_dispatch:
    inputs:
      save:
        description: 'Save reflection to Firestore?'
        required: false
        default: 'true'

jobs:
  run-daily-summary:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/1021320164820/locations/global/workloadIdentityPools/selfos-pool/providers/github-provider'
          service_account: 'github-actions-sa@selfos-test.iam.gserviceaccount.com'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Inject secrets
        run: |
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" > .env

      - name: Run daily summary
        id: summary
        run: |
          if [ "${{ github.event_name }}" = "schedule" ] || [ "${{ github.event.inputs.save }}" = "true" ]; then
            npm run summary -- --save > summary_output.txt
          else
            npm run summary > summary_output.txt
          fi

      - name: Send Discord summary
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          echo "📤 Posting summary to Discord..."
          MAX_LEN=1900
          CONTENT=$(cat summary_output.txt)

          # Truncate to safe size if needed
          if [ ${#CONTENT} -gt $MAX_LEN ]; then
            CONTENT="${CONTENT:0:$MAX_LEN}..."
          fi

          PAYLOAD=$(jq -n --arg content "$CONTENT" '{content: $content}')
          curl -X POST -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "$DISCORD_WEBHOOK_URL"

      - name: Cleanup
        run: rm -f .env summary_output.txt